ERROR: Function Main.main contains unsafe instructions but is not marked as unsafe or safe
 ---> ./test/errors/safety/missing_safe_extern_call/main.sk:5:4
 | 5 fn main() {
