ERROR: Named argument x in dynamic function call is not supported
 ---> ./test/errors/named_arg/named_arg_in_dynamic_call/main.sk:4:7
 | 4     f(x: 10)
